import Head from "next/head";
import Counter from "../components/Counter";

export default function Home() {
  return (
    <div className="bg-[#573391] h-screen w-screen text-white font-semibold text-xl flex items-center justify-center">
      <Head>
        <title>Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Counter />
      </main>
    </div>
  );
}
